//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    /// Color `AccentColor`.
    static let accentColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "AccentColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func accentColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.accentColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(watchOS)
    /// `UIColor(named: "AccentColor", bundle: ..., traitCollection: ...)`
    @available(watchOSApplicationExtension 4.0, *)
    static func accentColor(_: Void = ()) -> UIKit.UIColor? {
      return UIKit.UIColor(named: R.color.accentColor.name)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `appicon.launch`.
    static let appiconLaunch = Rswift.ImageResource(bundle: R.hostingBundle, name: "appicon.launch")
    /// Image `image.loaded`.
    static let imageLoaded = Rswift.ImageResource(bundle: R.hostingBundle, name: "image.loaded")
    /// Image `share.button`.
    static let shareButton = Rswift.ImageResource(bundle: R.hostingBundle, name: "share.button")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "appicon.launch", bundle: ..., traitCollection: ...)`
    static func appiconLaunch(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.appiconLaunch, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "image.loaded", bundle: ..., traitCollection: ...)`
    static func imageLoaded(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.imageLoaded, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "share.button", bundle: ..., traitCollection: ...)`
    static func shareButton(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.shareButton, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    /// This `R.string.alert` struct is generated, and contains static references to 9 localization keys.
    struct alert {
      /// en translation: Are you sure you want to log out?
      ///
      /// Locales: en, ru
      static let logout_text = Rswift.StringResource(key: "logout_text", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Authorized successfull
      ///
      /// Locales: en, ru
      static let successful_authorization = Rswift.StringResource(key: "successful_authorization", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Cancel
      ///
      /// Locales: en, ru
      static let cancel_title = Rswift.StringResource(key: "cancel_title", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Data have been read wrong
      ///
      /// Locales: en, ru
      static let wrong_data = Rswift.StringResource(key: "wrong_data", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Image saved to camera roll
      ///
      /// Locales: en, ru
      static let image_saved = Rswift.StringResource(key: "image_saved", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: No response sent
      ///
      /// Locales: en, ru
      static let no_response = Rswift.StringResource(key: "no_response", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Some error occured. Please, write to the support.
      ///
      /// Locales: en, ru
      static let unexpected_error = Rswift.StringResource(key: "unexpected_error", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Token has expired. Please log in again.
      ///
      /// Locales: en, ru
      static let expired_token = Rswift.StringResource(key: "expired_token", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: image can't be loaded
      ///
      /// Locales: en, ru
      static let image_wrong = Rswift.StringResource(key: "image_wrong", tableName: "Alert", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)

      /// en translation: Are you sure you want to log out?
      ///
      /// Locales: en, ru
      static func logout_text(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("logout_text", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "logout_text"
        }

        return NSLocalizedString("logout_text", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: Authorized successfull
      ///
      /// Locales: en, ru
      static func successful_authorization(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("successful_authorization", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "successful_authorization"
        }

        return NSLocalizedString("successful_authorization", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: Cancel
      ///
      /// Locales: en, ru
      static func cancel_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("cancel_title", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "cancel_title"
        }

        return NSLocalizedString("cancel_title", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: Data have been read wrong
      ///
      /// Locales: en, ru
      static func wrong_data(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("wrong_data", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "wrong_data"
        }

        return NSLocalizedString("wrong_data", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: Image saved to camera roll
      ///
      /// Locales: en, ru
      static func image_saved(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("image_saved", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "image_saved"
        }

        return NSLocalizedString("image_saved", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: No response sent
      ///
      /// Locales: en, ru
      static func no_response(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("no_response", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "no_response"
        }

        return NSLocalizedString("no_response", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: Some error occured. Please, write to the support.
      ///
      /// Locales: en, ru
      static func unexpected_error(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("unexpected_error", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "unexpected_error"
        }

        return NSLocalizedString("unexpected_error", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: Token has expired. Please log in again.
      ///
      /// Locales: en, ru
      static func expired_token(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("expired_token", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "expired_token"
        }

        return NSLocalizedString("expired_token", tableName: "Alert", bundle: bundle, comment: "")
      }

      /// en translation: image can't be loaded
      ///
      /// Locales: en, ru
      static func image_wrong(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("image_wrong", tableName: "Alert", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Alert", preferredLanguages: preferredLanguages) else {
          return "image_wrong"
        }

        return NSLocalizedString("image_wrong", tableName: "Alert", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    /// This `R.string.appLoc` struct is generated, and contains static references to 3 localization keys.
    struct appLoc {
      /// en translation: Exit
      ///
      /// Locales: en, ru
      static let exit_button_title = Rswift.StringResource(key: "exit_button_title", tableName: "AppLoc", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Login with VK
      ///
      /// Locales: en, ru
      static let sign_in_button_title = Rswift.StringResource(key: "sign_in_button_title", tableName: "AppLoc", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)
      /// en translation: Mobile Up Gallery
      ///
      /// Locales: en, ru
      static let self_title = Rswift.StringResource(key: "self_title", tableName: "AppLoc", bundle: R.hostingBundle, locales: ["en", "ru"], comment: nil)

      /// en translation: Exit
      ///
      /// Locales: en, ru
      static func exit_button_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("exit_button_title", tableName: "AppLoc", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "AppLoc", preferredLanguages: preferredLanguages) else {
          return "exit_button_title"
        }

        return NSLocalizedString("exit_button_title", tableName: "AppLoc", bundle: bundle, comment: "")
      }

      /// en translation: Login with VK
      ///
      /// Locales: en, ru
      static func sign_in_button_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("sign_in_button_title", tableName: "AppLoc", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "AppLoc", preferredLanguages: preferredLanguages) else {
          return "sign_in_button_title"
        }

        return NSLocalizedString("sign_in_button_title", tableName: "AppLoc", bundle: bundle, comment: "")
      }

      /// en translation: Mobile Up Gallery
      ///
      /// Locales: en, ru
      static func self_title(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("self_title", tableName: "AppLoc", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "AppLoc", preferredLanguages: preferredLanguages) else {
          return "self_title"
        }

        return NSLocalizedString("self_title", tableName: "AppLoc", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if UIKit.UIImage(named: "appicon.launch", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'appicon.launch' is used in storyboard 'LaunchScreen', but couldn't be loaded.") }
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
